// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvnyhgbthylvauedesbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2bnloZ2J0aHlsdmF1ZWRlc2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDcxMTgsImV4cCI6MjA3MjcyMzExOH0.GDXhBTfY-ZRhgnklaIjvh66j1XMqAHETeoliEcgcMZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});